<div style="font-family: Arial, sans-serif; text-align: left;">
    <h2></h2>
    <ol>
        <li>La promozione è valida esclusivamente per tutti quei giocatori che si registrano sul portale Netbet.it su desktop o mobile e che hanno effettuato un deposito sul sito sport e convalidato il conto (tramite invio del documento a info@netbet.it) prima di piazzare la scommessa.<br><br></li>
        <li>Termini e condizioni aggiornati al 7 Dicembre 2016.</li>
        <li>Una volta effettuato il primo deposito sul sito sport e piazzata la prima giocata da almeno 5€ (entro massimo 3 giorni dal deposito e con quota minima di 1,70 in singola e, in caso di multipla, con quota 1.70 per ogni evento), riceverai automaticamente un bonus del 50% fino ad un massimo di 200€ sulla tua prima scommessa nel caso in cui dovesse risultare perdente.<br><br></li>
        <li>Saranno considerate valide le scommesse piazzate in singola e in multipla pre-match e/o live, mentre quelle a sistema non sono valide ai fini dell'offerta. Le scommesse annullate inoltre non saranno eleggibili.<br><br></li>
        <li>Il bonus Benvenuto verrà accreditato automaticamente una volta che la schedina viene refertata da AAMS e non è prelevabile.<br><br></li>
        <li>Sono prelevabili le eventuali vincite derivanti dal bonus solo dopo che è stato scommesso 8 volte entro il termine di validità dello stesso, solo per scommesse aventi quota totale minima di 1,70. Pertanto il bonus verrà rimosso alla scadenza del periodo di 30 giorni se non è stato conseguito il Requisito di scommessa.<br><br></li>
        <li>Una volta che vengono rispettati i requisiti di scommessa, tutte le vincite inziando da quella dell'attuale scommessa vengono trasferite nel saldo reale e possono essere prelevate.<br><br></li>
        <li>Se esiste qualche saldo bonus che non è stato utilizzato nella scommessa, rimarrà bonus fino a quando non verrà scommesso.<br><br></li>
        <li>Maggiori dettagli riguardo il nostro sistema di bonus sono disponibili su FAQ &gt; Bonus.<br><br></li>
        <li>Se la tua prima scommessa è stata confermata prima che il tuo conto venisse convalidato, non riceverai automaticamente il bonus benvenuto. In questo caso dovrai convalidare il conto e inviare una email al nostro servizio assistenza all'indirizzo <a href="mailto:info@netbet.it">info@netbet.it</a> e richiedere il bonus.<br><br></li>
        <li>Il giocatore riceve il bonus che rimane in sospeso fino a quando non viene attivato da Mio Conto &gt; Bonus Sport &gt; Dettagli bonus sport. Una volta che il giocatore ha attivato il suo bonus, l'importo viene spostato nel suo Saldo bonus. Il bonus non potrà essere giocato su sistemi.<br><br></li>
        <li>Quando il giocatore ha soldi e bonus nel saldo, i soldi vengono usati per primi e, solo dopo che si raggiunge importo 0€, verrá usato il Saldo Bonus.<br><br></li>
        <li>Le scommesse effettuate parzialmente o totalmente con somme provenienti da bonus o crediti residui non parteciperanno al ricevimento di ulteriori bonus. Sarà rimborsato esclusivamente un importo massimo pari al valore del deposito utilizzato per piazzare la prima scommessa.<br><br></li>
        <li>Per ricevere il bonus é necessario aver giocato i bonus precedentemente ricevuti. I bonus inferiori a 1 euro non potranno essere immediatamente utilizzati ma verranno aggiunti ai bonus successivamente accreditati.<br><br></li>
        <li>Se il giocatore effettua un prelievo prima che i requisiti di scommessa siano stati soddisfatti, successivamente i bonus e le vincite vengono cancellate e rimosse dal proprio Saldo Bonus.<br><br></li>
        <li>L'offerta è limitata ad 1 per persona, conto di gioco, carta di credito, indirizzo email, numero di telefono ed indirizzo IP. Qualora dovesse essere rilevato un comportamento scorretto e/o fraudolento da parte del giocatore, Netbet si riserva il diritto, a propria esclusiva discrezione, di escludere il giocatore dalla promozione e/o limitarne il conto di gioco.<br><br></li>
        <li>Nel caso un giocatore adotti comportamenti fraudolenti o in violazione della normativa applicabile l'erogazione dei bonus già attribuiti sarà annullata con la rimozione del bonus e delle vincite conseguite tramite l'utilizzo dello stesso, nessun successivo bonus sarà attribuito e il giocatore sarà escluso dalla promozione.<br><br></li>
        <li>In conformità con la normativa AAMS, i bonus attribuiti non saranno prelevabili (neanche in caso di chiusura del conto di gioco) e devono essere giocati almeno una volta sulla piattaforma Netbet.it per poter prelevare le vincite derivanti dal loro utilizzo.<br><br></li>
        <li>Non è possibile usufruire di più di un bonus per lo stesso deposito. Se non si rispettano totalmente i presenti termini e condizioni, si rinuncerà automaticamente al bonus.<br><br></li>
        <li>NetBet si riserva il diritto di modificare i termini delle promozioni senza alcun preavviso.</li>
        <li>Per visualizzare lo stato dei tuoi bonus sport basta effettuare il login e cliccare su <strong>Mio conto &gt; Bonus Sport &gt; Dettagli Bonus Sport</strong></li>
    </ol>
</div>